name: multilat
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - numpy=1.23.3
  - python=3.10.10
  - pip=23.0.1
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - pip:
    - opencv-python==4.7.0.72
    - scikit-image==0.21.0
    - scipy==1.9.1
    - gdown
