# Input data
resolution: 1024                 
age_min: 20                  
age_max: 70  
# Training hyperparameters                 
batch_size: 1
epochs: 1
truncation_psi: 0.5
# Optimizer parameters               
lr: 0.001         
beta_1: 0.9                   
beta_2: 0.999
weight_decay: 0.0005  
# Learning rate scheduler                  
step_size: 10                
gamma: 0.1                                 
# Tensorboard log options
image_save_iter: 50
image_log_iter: 50
log_iter: 1                  
# Networks
net_type: 17
mapping_layers: 18
mapping_fmaps: 512
mapping_lrmul: 1
mapping_nonlinearity: 'linear'
bottleneck_size: 1
# Classifier
cls_type: 1
latent_cls_type: 3013
# Attributes
# attr: 'Bald,Attractive,Male,Wearing_Lipstick,Smiling,Eyeglasses,Big_Lips,High_Cheekbones,Young,Gray_Hair,No_Beard,Blond_Hair,Big_Nose,Bushy_Eyebrows,Pale_Skin,Chubby,Narrow_Eyes,Wavy_Hair,Bangs,Arched_Eyebrows'
# attr: 'Bald,Attractive,Male,Wearing_Lipstick'
attr: 'Bald,Smiling,Male'
# Loss weight
corr_threshold: 1
w:
  pb: 1
  recon: 10
  reg: 1
